import { useRouter } from 'next/router';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowLeft } from '@fortawesome/free-solid-svg-icons';

import useStore from '../../helpers/store';

import classes from '../../styles/Pages/ProjectPage.module.css';

import { ProjectInfo } from '../../helpers/content';
import NavBar from '../../components/Navigation/NavBar';
import Link from 'next/link';

const ProjectId: NextPage = () => {
  const router = useRouter();
  const projectId = router.query.projectId;
  const { theme } = useStore();

  const project = ProjectInfo[0];

  return (
    <main className={classes['main-body']} data-theme={theme}>
      <Head>
        <title>Test Project Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.container}>
        <Link href="/">
          <div className={classes.return}>
            <FontAwesomeIcon icon={faArrowLeft} /> Go Back
          </div>
        </Link>

        <div className={classes['image-container']}>
          <Image
            layout="fill"
            objectFit="contain"
            src={project.photos.mobile}
          />
        </div>
        <div className={classes['title-container']}>
          <h2 className={classes.title}>{project.title}</h2>
          <h4 className={classes.date}>{project.date}</h4>
          <div className={classes.border}></div>
        </div>
        <div className={classes['description-container']}>
          <p className={classes.tech}>{project.tech}</p>
          <p className={classes.description}>{project.desc}</p>
        </div>
        <div className={classes['border-alt']}></div>
        <div className={classes['btn-container']}>
          <a
            role="button"
            href={project.links.github}
            target="_blank"
            className={classes.github}
          >
            GitHub
          </a>
          <a
            role="button"
            href={project.links.view}
            target="_blank"
            className={classes['live-site']}
          >
            View Site
          </a>
        </div>
      </div>
    </main>
  );
};

export default ProjectId;
