import type { NextPage } from 'next';
import Head from 'next/head';

import useStore from '../helpers/store';

import Jumbotron from '../components/Jumbotron';
import Projects from '../components/Projects';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { theme } = useStore();
  return (
    <main className={styles.container} data-theme={theme}>
      <Head>
        <title>Logan Ricard | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Jumbotron />
      <Projects />
    </main>
  );
};

export default Home;
